/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthedAircraftRouteImport } from './routes/_authed/aircraft'
import { Route as AuthedBillingRouteImport } from './routes/_authed/billing'
import { Route as AuthedBillingRegisterRedirectRouteImport } from './routes/_authed/billing-register-redirect'
import { Route as AuthedComplianceRouteImport } from './routes/_authed/compliance'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedDeveloperRouteImport } from './routes/_authed/developer'
import { Route as AuthedFacilitiesRouteImport } from './routes/_authed/facilities'
import { Route as AuthedMaintenanceRouteImport } from './routes/_authed/maintenance'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed/notifications'
import { Route as AuthedPeopleRouteImport } from './routes/_authed/people'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedScheduleRouteImport } from './routes/_authed/schedule'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthedMeIndexRouteImport } from './routes/_authed/me/index'
import { Route as AuthedMeAvailabilityRouteImport } from './routes/_authed/me/availability'
import { Route as AuthedMeBookRouteImport } from './routes/_authed/me/book'
import { Route as AuthedMeCurrenciesRouteImport } from './routes/_authed/me/currencies'
import { Route as AuthedMeDocumentsRouteImport } from './routes/_authed/me/documents'
import { Route as AuthedMeInvoicesRouteImport } from './routes/_authed/me/invoices'
import { Route as AuthedMePaymentMethodsRouteImport } from './routes/_authed/me/payment-methods'
import { Route as AuthedMeProfileRouteImport } from './routes/_authed/me/profile'
import { Route as AuthedMeScheduleRouteImport } from './routes/_authed/me/schedule'
import { Route as AuthedOperationsCancellationsRouteImport } from './routes/_authed/operations/cancellations'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedSettingsIntegrationsQuickbooksRouteImport } from './routes/_authed/settings/integrations/quickbooks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAircraftRoute = AuthedAircraftRouteImport.update({
  id: '/aircraft',
  path: '/aircraft',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBillingRoute = AuthedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBillingRegisterRedirectRoute =
  AuthedBillingRegisterRedirectRouteImport.update({
    id: '/billing-register-redirect',
    path: '/billing-register-redirect',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedComplianceRoute = AuthedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDeveloperRoute = AuthedDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFacilitiesRoute = AuthedFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMaintenanceRoute = AuthedMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeopleRoute = AuthedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedScheduleRoute = AuthedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMeIndexRoute = AuthedMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeAvailabilityRoute = AuthedMeAvailabilityRouteImport.update({
  id: '/me/availability',
  path: '/me/availability',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeBookRoute = AuthedMeBookRouteImport.update({
  id: '/me/book',
  path: '/me/book',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeCurrenciesRoute = AuthedMeCurrenciesRouteImport.update({
  id: '/me/currencies',
  path: '/me/currencies',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeDocumentsRoute = AuthedMeDocumentsRouteImport.update({
  id: '/me/documents',
  path: '/me/documents',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeInvoicesRoute = AuthedMeInvoicesRouteImport.update({
  id: '/me/invoices',
  path: '/me/invoices',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMePaymentMethodsRoute = AuthedMePaymentMethodsRouteImport.update({
  id: '/me/payment-methods',
  path: '/me/payment-methods',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeProfileRoute = AuthedMeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeScheduleRoute = AuthedMeScheduleRouteImport.update({
  id: '/me/schedule',
  path: '/me/schedule',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOperationsCancellationsRoute =
  AuthedOperationsCancellationsRouteImport.update({
    id: '/operations/cancellations',
    path: '/operations/cancellations',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIntegrationsQuickbooksRoute =
  AuthedSettingsIntegrationsQuickbooksRouteImport.update({
    id: '/settings/integrations/quickbooks',
    path: '/settings/integrations/quickbooks',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/aircraft': typeof AuthedAircraftRoute
  '/billing': typeof AuthedBillingRoute
  '/billing-register-redirect': typeof AuthedBillingRegisterRedirectRoute
  '/compliance': typeof AuthedComplianceRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/developer': typeof AuthedDeveloperRoute
  '/facilities': typeof AuthedFacilitiesRoute
  '/maintenance': typeof AuthedMaintenanceRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/people': typeof AuthedPeopleRoute
  '/reports': typeof AuthedReportsRoute
  '/schedule': typeof AuthedScheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/me/availability': typeof AuthedMeAvailabilityRoute
  '/me/book': typeof AuthedMeBookRoute
  '/me/currencies': typeof AuthedMeCurrenciesRoute
  '/me/documents': typeof AuthedMeDocumentsRoute
  '/me/invoices': typeof AuthedMeInvoicesRoute
  '/me/payment-methods': typeof AuthedMePaymentMethodsRoute
  '/me/profile': typeof AuthedMeProfileRoute
  '/me/schedule': typeof AuthedMeScheduleRoute
  '/operations/cancellations': typeof AuthedOperationsCancellationsRoute
  '/me/': typeof AuthedMeIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/settings/integrations/quickbooks': typeof AuthedSettingsIntegrationsQuickbooksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/aircraft': typeof AuthedAircraftRoute
  '/billing': typeof AuthedBillingRoute
  '/billing-register-redirect': typeof AuthedBillingRegisterRedirectRoute
  '/compliance': typeof AuthedComplianceRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/developer': typeof AuthedDeveloperRoute
  '/facilities': typeof AuthedFacilitiesRoute
  '/maintenance': typeof AuthedMaintenanceRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/people': typeof AuthedPeopleRoute
  '/reports': typeof AuthedReportsRoute
  '/schedule': typeof AuthedScheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/me/availability': typeof AuthedMeAvailabilityRoute
  '/me/book': typeof AuthedMeBookRoute
  '/me/currencies': typeof AuthedMeCurrenciesRoute
  '/me/documents': typeof AuthedMeDocumentsRoute
  '/me/invoices': typeof AuthedMeInvoicesRoute
  '/me/payment-methods': typeof AuthedMePaymentMethodsRoute
  '/me/profile': typeof AuthedMeProfileRoute
  '/me/schedule': typeof AuthedMeScheduleRoute
  '/operations/cancellations': typeof AuthedOperationsCancellationsRoute
  '/me': typeof AuthedMeIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/settings/integrations/quickbooks': typeof AuthedSettingsIntegrationsQuickbooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authed/aircraft': typeof AuthedAircraftRoute
  '/_authed/billing': typeof AuthedBillingRoute
  '/_authed/billing-register-redirect': typeof AuthedBillingRegisterRedirectRoute
  '/_authed/compliance': typeof AuthedComplianceRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/developer': typeof AuthedDeveloperRoute
  '/_authed/facilities': typeof AuthedFacilitiesRoute
  '/_authed/maintenance': typeof AuthedMaintenanceRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/people': typeof AuthedPeopleRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/schedule': typeof AuthedScheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authed/me/availability': typeof AuthedMeAvailabilityRoute
  '/_authed/me/book': typeof AuthedMeBookRoute
  '/_authed/me/currencies': typeof AuthedMeCurrenciesRoute
  '/_authed/me/documents': typeof AuthedMeDocumentsRoute
  '/_authed/me/invoices': typeof AuthedMeInvoicesRoute
  '/_authed/me/payment-methods': typeof AuthedMePaymentMethodsRoute
  '/_authed/me/profile': typeof AuthedMeProfileRoute
  '/_authed/me/schedule': typeof AuthedMeScheduleRoute
  '/_authed/operations/cancellations': typeof AuthedOperationsCancellationsRoute
  '/_authed/me/': typeof AuthedMeIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/settings/integrations/quickbooks': typeof AuthedSettingsIntegrationsQuickbooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/aircraft'
    | '/billing'
    | '/billing-register-redirect'
    | '/compliance'
    | '/dashboard'
    | '/developer'
    | '/facilities'
    | '/maintenance'
    | '/notifications'
    | '/people'
    | '/reports'
    | '/schedule'
    | '/auth/callback'
    | '/me/availability'
    | '/me/book'
    | '/me/currencies'
    | '/me/documents'
    | '/me/invoices'
    | '/me/payment-methods'
    | '/me/profile'
    | '/me/schedule'
    | '/operations/cancellations'
    | '/me/'
    | '/settings/'
    | '/settings/integrations/quickbooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/aircraft'
    | '/billing'
    | '/billing-register-redirect'
    | '/compliance'
    | '/dashboard'
    | '/developer'
    | '/facilities'
    | '/maintenance'
    | '/notifications'
    | '/people'
    | '/reports'
    | '/schedule'
    | '/auth/callback'
    | '/me/availability'
    | '/me/book'
    | '/me/currencies'
    | '/me/documents'
    | '/me/invoices'
    | '/me/payment-methods'
    | '/me/profile'
    | '/me/schedule'
    | '/operations/cancellations'
    | '/me'
    | '/settings'
    | '/settings/integrations/quickbooks'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_authed/aircraft'
    | '/_authed/billing'
    | '/_authed/billing-register-redirect'
    | '/_authed/compliance'
    | '/_authed/dashboard'
    | '/_authed/developer'
    | '/_authed/facilities'
    | '/_authed/maintenance'
    | '/_authed/notifications'
    | '/_authed/people'
    | '/_authed/reports'
    | '/_authed/schedule'
    | '/auth/callback'
    | '/_authed/me/availability'
    | '/_authed/me/book'
    | '/_authed/me/currencies'
    | '/_authed/me/documents'
    | '/_authed/me/invoices'
    | '/_authed/me/payment-methods'
    | '/_authed/me/profile'
    | '/_authed/me/schedule'
    | '/_authed/operations/cancellations'
    | '/_authed/me/'
    | '/_authed/settings/'
    | '/_authed/settings/integrations/quickbooks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/aircraft': {
      id: '/_authed/aircraft'
      path: '/aircraft'
      fullPath: '/aircraft'
      preLoaderRoute: typeof AuthedAircraftRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/billing': {
      id: '/_authed/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthedBillingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/billing-register-redirect': {
      id: '/_authed/billing-register-redirect'
      path: '/billing-register-redirect'
      fullPath: '/billing-register-redirect'
      preLoaderRoute: typeof AuthedBillingRegisterRedirectRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/compliance': {
      id: '/_authed/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthedComplianceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/developer': {
      id: '/_authed/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AuthedDeveloperRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/facilities': {
      id: '/_authed/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof AuthedFacilitiesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/maintenance': {
      id: '/_authed/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthedMaintenanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/people': {
      id: '/_authed/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthedPeopleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedule': {
      id: '/_authed/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthedScheduleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/me/': {
      id: '/_authed/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof AuthedMeIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/availability': {
      id: '/_authed/me/availability'
      path: '/me/availability'
      fullPath: '/me/availability'
      preLoaderRoute: typeof AuthedMeAvailabilityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/book': {
      id: '/_authed/me/book'
      path: '/me/book'
      fullPath: '/me/book'
      preLoaderRoute: typeof AuthedMeBookRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/currencies': {
      id: '/_authed/me/currencies'
      path: '/me/currencies'
      fullPath: '/me/currencies'
      preLoaderRoute: typeof AuthedMeCurrenciesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/documents': {
      id: '/_authed/me/documents'
      path: '/me/documents'
      fullPath: '/me/documents'
      preLoaderRoute: typeof AuthedMeDocumentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/invoices': {
      id: '/_authed/me/invoices'
      path: '/me/invoices'
      fullPath: '/me/invoices'
      preLoaderRoute: typeof AuthedMeInvoicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/payment-methods': {
      id: '/_authed/me/payment-methods'
      path: '/me/payment-methods'
      fullPath: '/me/payment-methods'
      preLoaderRoute: typeof AuthedMePaymentMethodsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/profile': {
      id: '/_authed/me/profile'
      path: '/me/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof AuthedMeProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/schedule': {
      id: '/_authed/me/schedule'
      path: '/me/schedule'
      fullPath: '/me/schedule'
      preLoaderRoute: typeof AuthedMeScheduleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/operations/cancellations': {
      id: '/_authed/operations/cancellations'
      path: '/operations/cancellations'
      fullPath: '/operations/cancellations'
      preLoaderRoute: typeof AuthedOperationsCancellationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/integrations/quickbooks': {
      id: '/_authed/settings/integrations/quickbooks'
      path: '/settings/integrations/quickbooks'
      fullPath: '/settings/integrations/quickbooks'
      preLoaderRoute: typeof AuthedSettingsIntegrationsQuickbooksRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAircraftRoute: typeof AuthedAircraftRoute
  AuthedBillingRoute: typeof AuthedBillingRoute
  AuthedBillingRegisterRedirectRoute: typeof AuthedBillingRegisterRedirectRoute
  AuthedComplianceRoute: typeof AuthedComplianceRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDeveloperRoute: typeof AuthedDeveloperRoute
  AuthedFacilitiesRoute: typeof AuthedFacilitiesRoute
  AuthedMaintenanceRoute: typeof AuthedMaintenanceRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedPeopleRoute: typeof AuthedPeopleRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedScheduleRoute: typeof AuthedScheduleRoute
  AuthedMeAvailabilityRoute: typeof AuthedMeAvailabilityRoute
  AuthedMeBookRoute: typeof AuthedMeBookRoute
  AuthedMeCurrenciesRoute: typeof AuthedMeCurrenciesRoute
  AuthedMeDocumentsRoute: typeof AuthedMeDocumentsRoute
  AuthedMeInvoicesRoute: typeof AuthedMeInvoicesRoute
  AuthedMePaymentMethodsRoute: typeof AuthedMePaymentMethodsRoute
  AuthedMeProfileRoute: typeof AuthedMeProfileRoute
  AuthedMeScheduleRoute: typeof AuthedMeScheduleRoute
  AuthedOperationsCancellationsRoute: typeof AuthedOperationsCancellationsRoute
  AuthedMeIndexRoute: typeof AuthedMeIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedSettingsIntegrationsQuickbooksRoute: typeof AuthedSettingsIntegrationsQuickbooksRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAircraftRoute: AuthedAircraftRoute,
  AuthedBillingRoute: AuthedBillingRoute,
  AuthedBillingRegisterRedirectRoute: AuthedBillingRegisterRedirectRoute,
  AuthedComplianceRoute: AuthedComplianceRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDeveloperRoute: AuthedDeveloperRoute,
  AuthedFacilitiesRoute: AuthedFacilitiesRoute,
  AuthedMaintenanceRoute: AuthedMaintenanceRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedPeopleRoute: AuthedPeopleRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedScheduleRoute: AuthedScheduleRoute,
  AuthedMeAvailabilityRoute: AuthedMeAvailabilityRoute,
  AuthedMeBookRoute: AuthedMeBookRoute,
  AuthedMeCurrenciesRoute: AuthedMeCurrenciesRoute,
  AuthedMeDocumentsRoute: AuthedMeDocumentsRoute,
  AuthedMeInvoicesRoute: AuthedMeInvoicesRoute,
  AuthedMePaymentMethodsRoute: AuthedMePaymentMethodsRoute,
  AuthedMeProfileRoute: AuthedMeProfileRoute,
  AuthedMeScheduleRoute: AuthedMeScheduleRoute,
  AuthedOperationsCancellationsRoute: AuthedOperationsCancellationsRoute,
  AuthedMeIndexRoute: AuthedMeIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedSettingsIntegrationsQuickbooksRoute:
    AuthedSettingsIntegrationsQuickbooksRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
