/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthedAircraftRouteImport } from './routes/_authed/aircraft'
import { Route as AuthedBillingRouteImport } from './routes/_authed/billing'
import { Route as AuthedComplianceRouteImport } from './routes/_authed/compliance'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedFacilitiesRouteImport } from './routes/_authed/facilities'
import { Route as AuthedMaintenanceRouteImport } from './routes/_authed/maintenance'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed/notifications'
import { Route as AuthedPeopleRouteImport } from './routes/_authed/people'
import { Route as AuthedScheduleRouteImport } from './routes/_authed/schedule'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedMeIndexRouteImport } from './routes/_authed/me/index'
import { Route as AuthedMeAvailabilityRouteImport } from './routes/_authed/me/availability'
import { Route as AuthedMeBookRouteImport } from './routes/_authed/me/book'
import { Route as AuthedMeCurrenciesRouteImport } from './routes/_authed/me/currencies'
import { Route as AuthedMeInvoicesRouteImport } from './routes/_authed/me/invoices'
import { Route as AuthedMePaymentMethodsRouteImport } from './routes/_authed/me/payment-methods'
import { Route as AuthedMeProfileRouteImport } from './routes/_authed/me/profile'
import { Route as AuthedMeScheduleRouteImport } from './routes/_authed/me/schedule'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAircraftRoute = AuthedAircraftRouteImport.update({
  id: '/aircraft',
  path: '/aircraft',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBillingRoute = AuthedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedComplianceRoute = AuthedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFacilitiesRoute = AuthedFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMaintenanceRoute = AuthedMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeopleRoute = AuthedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedScheduleRoute = AuthedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeIndexRoute = AuthedMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeAvailabilityRoute = AuthedMeAvailabilityRouteImport.update({
  id: '/me/availability',
  path: '/me/availability',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeBookRoute = AuthedMeBookRouteImport.update({
  id: '/me/book',
  path: '/me/book',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeCurrenciesRoute = AuthedMeCurrenciesRouteImport.update({
  id: '/me/currencies',
  path: '/me/currencies',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeInvoicesRoute = AuthedMeInvoicesRouteImport.update({
  id: '/me/invoices',
  path: '/me/invoices',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMePaymentMethodsRoute = AuthedMePaymentMethodsRouteImport.update({
  id: '/me/payment-methods',
  path: '/me/payment-methods',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeProfileRoute = AuthedMeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeScheduleRoute = AuthedMeScheduleRouteImport.update({
  id: '/me/schedule',
  path: '/me/schedule',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/aircraft': typeof AuthedAircraftRoute
  '/billing': typeof AuthedBillingRoute
  '/compliance': typeof AuthedComplianceRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/facilities': typeof AuthedFacilitiesRoute
  '/maintenance': typeof AuthedMaintenanceRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/people': typeof AuthedPeopleRoute
  '/schedule': typeof AuthedScheduleRoute
  '/settings': typeof AuthedSettingsRoute
  '/me/availability': typeof AuthedMeAvailabilityRoute
  '/me/book': typeof AuthedMeBookRoute
  '/me/currencies': typeof AuthedMeCurrenciesRoute
  '/me/invoices': typeof AuthedMeInvoicesRoute
  '/me/payment-methods': typeof AuthedMePaymentMethodsRoute
  '/me/profile': typeof AuthedMeProfileRoute
  '/me/schedule': typeof AuthedMeScheduleRoute
  '/me/': typeof AuthedMeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/aircraft': typeof AuthedAircraftRoute
  '/billing': typeof AuthedBillingRoute
  '/compliance': typeof AuthedComplianceRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/facilities': typeof AuthedFacilitiesRoute
  '/maintenance': typeof AuthedMaintenanceRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/people': typeof AuthedPeopleRoute
  '/schedule': typeof AuthedScheduleRoute
  '/settings': typeof AuthedSettingsRoute
  '/me/availability': typeof AuthedMeAvailabilityRoute
  '/me/book': typeof AuthedMeBookRoute
  '/me/currencies': typeof AuthedMeCurrenciesRoute
  '/me/invoices': typeof AuthedMeInvoicesRoute
  '/me/payment-methods': typeof AuthedMePaymentMethodsRoute
  '/me/profile': typeof AuthedMeProfileRoute
  '/me/schedule': typeof AuthedMeScheduleRoute
  '/me': typeof AuthedMeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authed/aircraft': typeof AuthedAircraftRoute
  '/_authed/billing': typeof AuthedBillingRoute
  '/_authed/compliance': typeof AuthedComplianceRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/facilities': typeof AuthedFacilitiesRoute
  '/_authed/maintenance': typeof AuthedMaintenanceRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/people': typeof AuthedPeopleRoute
  '/_authed/schedule': typeof AuthedScheduleRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/me/availability': typeof AuthedMeAvailabilityRoute
  '/_authed/me/book': typeof AuthedMeBookRoute
  '/_authed/me/currencies': typeof AuthedMeCurrenciesRoute
  '/_authed/me/invoices': typeof AuthedMeInvoicesRoute
  '/_authed/me/payment-methods': typeof AuthedMePaymentMethodsRoute
  '/_authed/me/profile': typeof AuthedMeProfileRoute
  '/_authed/me/schedule': typeof AuthedMeScheduleRoute
  '/_authed/me/': typeof AuthedMeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/aircraft'
    | '/billing'
    | '/compliance'
    | '/dashboard'
    | '/facilities'
    | '/maintenance'
    | '/notifications'
    | '/people'
    | '/schedule'
    | '/settings'
    | '/me/availability'
    | '/me/book'
    | '/me/currencies'
    | '/me/invoices'
    | '/me/payment-methods'
    | '/me/profile'
    | '/me/schedule'
    | '/me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/aircraft'
    | '/billing'
    | '/compliance'
    | '/dashboard'
    | '/facilities'
    | '/maintenance'
    | '/notifications'
    | '/people'
    | '/schedule'
    | '/settings'
    | '/me/availability'
    | '/me/book'
    | '/me/currencies'
    | '/me/invoices'
    | '/me/payment-methods'
    | '/me/profile'
    | '/me/schedule'
    | '/me'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/_authed/aircraft'
    | '/_authed/billing'
    | '/_authed/compliance'
    | '/_authed/dashboard'
    | '/_authed/facilities'
    | '/_authed/maintenance'
    | '/_authed/notifications'
    | '/_authed/people'
    | '/_authed/schedule'
    | '/_authed/settings'
    | '/_authed/me/availability'
    | '/_authed/me/book'
    | '/_authed/me/currencies'
    | '/_authed/me/invoices'
    | '/_authed/me/payment-methods'
    | '/_authed/me/profile'
    | '/_authed/me/schedule'
    | '/_authed/me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/aircraft': {
      id: '/_authed/aircraft'
      path: '/aircraft'
      fullPath: '/aircraft'
      preLoaderRoute: typeof AuthedAircraftRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/billing': {
      id: '/_authed/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthedBillingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/compliance': {
      id: '/_authed/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthedComplianceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/facilities': {
      id: '/_authed/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof AuthedFacilitiesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/maintenance': {
      id: '/_authed/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthedMaintenanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/people': {
      id: '/_authed/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthedPeopleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedule': {
      id: '/_authed/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthedScheduleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/': {
      id: '/_authed/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof AuthedMeIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/availability': {
      id: '/_authed/me/availability'
      path: '/me/availability'
      fullPath: '/me/availability'
      preLoaderRoute: typeof AuthedMeAvailabilityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/book': {
      id: '/_authed/me/book'
      path: '/me/book'
      fullPath: '/me/book'
      preLoaderRoute: typeof AuthedMeBookRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/currencies': {
      id: '/_authed/me/currencies'
      path: '/me/currencies'
      fullPath: '/me/currencies'
      preLoaderRoute: typeof AuthedMeCurrenciesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/invoices': {
      id: '/_authed/me/invoices'
      path: '/me/invoices'
      fullPath: '/me/invoices'
      preLoaderRoute: typeof AuthedMeInvoicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/payment-methods': {
      id: '/_authed/me/payment-methods'
      path: '/me/payment-methods'
      fullPath: '/me/payment-methods'
      preLoaderRoute: typeof AuthedMePaymentMethodsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/profile': {
      id: '/_authed/me/profile'
      path: '/me/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof AuthedMeProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/schedule': {
      id: '/_authed/me/schedule'
      path: '/me/schedule'
      fullPath: '/me/schedule'
      preLoaderRoute: typeof AuthedMeScheduleRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAircraftRoute: typeof AuthedAircraftRoute
  AuthedBillingRoute: typeof AuthedBillingRoute
  AuthedComplianceRoute: typeof AuthedComplianceRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedFacilitiesRoute: typeof AuthedFacilitiesRoute
  AuthedMaintenanceRoute: typeof AuthedMaintenanceRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedPeopleRoute: typeof AuthedPeopleRoute
  AuthedScheduleRoute: typeof AuthedScheduleRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedMeAvailabilityRoute: typeof AuthedMeAvailabilityRoute
  AuthedMeBookRoute: typeof AuthedMeBookRoute
  AuthedMeCurrenciesRoute: typeof AuthedMeCurrenciesRoute
  AuthedMeInvoicesRoute: typeof AuthedMeInvoicesRoute
  AuthedMePaymentMethodsRoute: typeof AuthedMePaymentMethodsRoute
  AuthedMeProfileRoute: typeof AuthedMeProfileRoute
  AuthedMeScheduleRoute: typeof AuthedMeScheduleRoute
  AuthedMeIndexRoute: typeof AuthedMeIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAircraftRoute: AuthedAircraftRoute,
  AuthedBillingRoute: AuthedBillingRoute,
  AuthedComplianceRoute: AuthedComplianceRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedFacilitiesRoute: AuthedFacilitiesRoute,
  AuthedMaintenanceRoute: AuthedMaintenanceRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedPeopleRoute: AuthedPeopleRoute,
  AuthedScheduleRoute: AuthedScheduleRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedMeAvailabilityRoute: AuthedMeAvailabilityRoute,
  AuthedMeBookRoute: AuthedMeBookRoute,
  AuthedMeCurrenciesRoute: AuthedMeCurrenciesRoute,
  AuthedMeInvoicesRoute: AuthedMeInvoicesRoute,
  AuthedMePaymentMethodsRoute: AuthedMePaymentMethodsRoute,
  AuthedMeProfileRoute: AuthedMeProfileRoute,
  AuthedMeScheduleRoute: AuthedMeScheduleRoute,
  AuthedMeIndexRoute: AuthedMeIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
